version: '3.7'
services:

  prep:
    image: 'iconloop/icon2-node'
    restart: "on-failure"
    container_name: "icon2-node"
    network_mode: "host"
    stdin_open: true
    cap_add:
      - SYS_TIME
    volumes:
      - ./data:/goloop/data
      - ./logs:/goloop/logs
      - ./config:/goloop/config

    environment:

      SERVICE: "${SERVICE:-MainNet}" # MainNet, SeJong
      GOLOOP_LOG_LEVEL: "debug" # trace, debug, info, warn, error, fatal, panic
      KEY_STORE_FILENAME: "${KEY_STORE_FILENAME:-keystore}" # e.g. keystore.json with file at config/keystore.json
      KEY_PASSWORD: "${KEY_PASSWORD}"
      FASTEST_START: "true"
      MIG_ENDPOINT: "${MIG_ENDPOINT}"
      ROLE: 3  # preps = 3, citizen = 0
